---
- hosts: all
  tasks:
    - name: Install some basic packages to make the system useful
      pacman:
        name:
          - base-devel
          - bind-tools
          - curl
          - emacs
          - git
          - gnupg
          - screen
          - source-highlight
          - stow
      tags:
        - pacman
    - name: Ensure basic ufw service configuration
      block:
        - name: Install the ufw service
          pacman:
            name:
              - ufw
          tags:
            - pacman
        - name: Enable and start the ufw service
          systemd:
            name: ufw
            enabled: yes
            state: started
        - name: Allow incoming ssh traffic through the firewall
          ufw:
            rule: allow
            to_port: ssh
            proto: tcp
        - name: Enable firewall
          ufw:
            default: deny
            logging: 'on'
            state: enabled
      tags:
        - ufw
- hosts: basicx
  tasks:
    - name: Install packages for a basic machine with X
      pacman:
        name:
          - alsa-utils
          - chromium
          - feh
          - ratpoison
          - rxvt-unicode
          - rxvt-unicode-terminfo
          - ttf-inconsolata
          - xdm-archlinux
          - xlockmore
          - xorg-server
          - xterm
      tags:
        - pacman
    - name: Enable and start the xdm service
      systemd:
        name: xdm-archlinux
        enabled: yes
        state: started
      tags:
        - xdm
- hosts: cisa
  tasks:
    - name: Install dev packages
      pacman:
        name:
          - ansible
          - terraform
      tags:
        - pacman
