---
- hosts: install
  tasks:
    - name: Install minimum packages for a working machine
      pacman:
        name:
          - alsa-utils
          - chromium
          - emacs
          - feh
          - git
          - gnupg
          - ratpoison
          - rxvt-unicode
          - rxvt-unicode-terminfo
          - screen
          - stow
          - sudo
          - ttf-inconsolata
          - ufw
          - xdm-archlinux
          - xlockmore
          - xorg-server
          - xterm
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
    - name: Create user account
      user:
        name: '{{ user_name }}'
        password: '{{ user_password }}'
        groups:
          - wheel
        append: yes
        update_password: on_create
    - name: Copy authorized keys
      authorized_key:
        user: '{{ user_name }}'
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
    - name: Give passwordless sudo access to wheel group
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel ALL='
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
    - name: Enable the xdm service
      systemd:
        name: xdm-archlinux
        enabled: yes
    - name: Revert the ssh config modifications that allowed root login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '{{ item.regex }}'
        line: '{{ item.line }}'
      loop:
        - {regex: PermitRootLogin yes, line: '#PermitRootLogin prohibit-password'}
        - {regex: ChallengeResponseAuthentication yes, line: ChallengeResponseAuthentication no}
    - name: Disable root password
      user:
        name: root
        password: '!'
    - name: Enable the ufw service
      systemd:
        name: ufw
        enabled: yes
        state: started
    - name: Allow incoming ssh traffic through the firewall
      ufw:
        rule: allow
        to_port: ssh
        proto: tcp
        log: yes
    - name: Enable firewall
      ufw:
        default: deny
        state: enabled
    - name: Shutdown
      command: shutdown -h now
